services:
  cv-depot:
    container_name: cv-depot
    image: cv-depot:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4200:9000"
      - "4280:8080"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
    volumes:
      - ../:/home/ubuntu/cv-depot
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
      - ~/Documents/images:/home/ubuntu/images
    working_dir: "/home/ubuntu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
