services:
  cv-toolbox:
    container_name: cv-toolbox
    image: cv-toolbox:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4200:9000"
      - "4280:8080"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
    volumes:
      - ../:/home/ubuntu/cv-toolbox
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
    working_dir: "/home/ubuntu"
